/**
 * Docholder — Gemini AI Service
 * API key loaded exclusively from process.env.GEMINI_API_KEY
 * Never hardcode keys here — always use the .env file.
 */

const https = require("https");

const GEMINI_MODEL = "gemini-2.0-flash-latest";
const GEMINI_BASE  = "generativelanguage.googleapis.com";

function getApiKey() {
    const key = process.env.GEMINI_API_KEY;
    if (!key) {
        throw new Error("GEMINI_API_KEY is not set in the environment. Add it to your .env file.");
    }
    return key;
}

function callGemini(prompt, options = {}) {
    return new Promise((resolve, reject) => {
        const apiKey = getApiKey();
        const body = JSON.stringify({
            contents: [{ parts: [{ text: prompt }] }],
            generationConfig: {
                temperature:     options.temperature     ?? 0.7,
                maxOutputTokens: options.maxOutputTokens ?? 2048,
                topP:            options.topP            ?? 0.9,
            }
        });
        const reqOptions = {
            hostname: GEMINI_BASE,
            path:     "/v1beta/models/" + GEMINI_MODEL + ":generateContent",
            method:   "POST",
            headers: {
                "Content-Type":   "application/json",
                "X-goog-api-key": apiKey,
                "Content-Length": Buffer.byteLength(body)
            }
        };
        const req = https.request(reqOptions, (res) => {
            let raw = "";
            res.on("data", chunk => { raw += chunk; });
            res.on("end", () => {
                try {
                    const json = JSON.parse(raw);
                    if (json.error) {
                        return reject(new Error("Gemini API error " + json.error.code + ": " + json.error.message));
                    }
                    const text = json && json.candidates && json.candidates[0] && json.candidates[0].content && json.candidates[0].content.parts && json.candidates[0].content.parts[0] && json.candidates[0].content.parts[0].text;
                    if (!text) return reject(new Error("Gemini returned an empty response."));
                    resolve(text.trim());
                } catch (e) {
                    reject(new Error("Failed to parse Gemini response: " + e.message));
                }
            });
        });
        req.on("error", (e) => reject(new Error("Gemini request failed: " + e.message)));
        req.setTimeout(30000, () => { req.destroy(); reject(new Error("Gemini request timed out after 30s")); });
        req.write(body);
        req.end();
    });
}

async function generateText(prompt, options) {
    if (!prompt || !prompt.trim()) throw new Error("Prompt cannot be empty.");
    return callGemini(prompt, options || {});
}

async function humanizeText(text, mode) {
    if (!text || !text.trim()) throw new Error("No text provided for humanization.");
    mode = mode || "Natural";
    const intensityMap = {
        Light:   "Make very minor edits to reduce AI-like phrasing while keeping the original structure mostly intact.",
        Natural: "Rewrite naturally as a human would, using varied sentence lengths, casual transitions, and conversational tone. Preserve all key information.",
        Strong:  "Aggressively rewrite in a human voice with diverse vocabulary, first-person perspective where appropriate, contractions, and varied sentence rhythm. Keep all facts intact."
    };
    const instruction = intensityMap[mode] || intensityMap["Natural"];
    const prompt = "You are a professional text editor specializing in making AI-generated content sound genuinely human.\n\nInstruction: " + instruction + "\n\nRules:\n- Do NOT add commentary or explanations before or after the text\n- Return ONLY the rewritten text, nothing else\n- Preserve the original meaning and all key information\n- Do not use these overly AI-typical phrases: furthermore, moreover, in conclusion, it is important to note, delve, tapestry, testament to, seamlessly, transformative\n\nText to humanize:\n\"\"\"\n" + text + "\n\"\"\"";
    return callGemini(prompt, { temperature: 0.85, maxOutputTokens: 4096 });
}

async function analyzeAiContent(text) {
    if (!text || !text.trim()) throw new Error("No text provided for analysis.");
    const prompt = "You are an expert AI content detector. Analyze the following text and assess the probability that it was generated by an AI (like ChatGPT, Claude, etc.) rather than a human.\n\nReturn your analysis ONLY as a valid JSON object with this exact structure:\n{\n  \"aiLikenessScore\": <number 0-100, where 100 = definitely AI>,\n  \"humanLikenessScore\": <number 0-100>,\n  \"confidence\": \"<Low|Medium|High>\",\n  \"verdict\": \"<brief one-line verdict>\",\n  \"signals\": [<up to 4 specific signals you detected>],\n  \"explanation\": \"<2-3 sentence explanation>\"\n}\n\nText to analyze:\n\"\"\"\n" + text.slice(0, 3000) + "\n\"\"\"";
    const raw = await callGemini(prompt, { temperature: 0.2, maxOutputTokens: 512 });
    const jsonMatch = raw.match(/\{[\s\S]*\}/);
    if (!jsonMatch) throw new Error("Gemini did not return valid JSON for AI analysis.");
    return JSON.parse(jsonMatch[0]);
}

async function summarizeText(text, format) {
    if (!text || !text.trim()) throw new Error("No text provided for summarization.");
    format = format || "bullet";
    const formatInstruction = { bullet: "Provide a concise bullet-point summary with 5-8 key points.", paragraph: "Write a concise 2-3 paragraph summary.", tldr: "Write a single TL;DR sentence (max 40 words) that captures the core message." }[format] || "Provide a concise bullet-point summary.";
    const prompt = "Summarize the following document. " + formatInstruction + "\nReturn ONLY the summary with no preamble, title, or explanation.\n\nDocument:\n\"\"\"\n" + text.slice(0, 6000) + "\n\"\"\"";
    return callGemini(prompt, { temperature: 0.4, maxOutputTokens: 1024 });
}

async function translateText(text, targetLanguage) {
    if (!text || !text.trim()) throw new Error("No text provided for translation.");
    if (!targetLanguage || !targetLanguage.trim()) throw new Error("Target language must be specified.");
    const prompt = "Translate the following text to " + targetLanguage + ".\nReturn ONLY the translated text with no explanation, preamble, or original text.\n\nText:\n\"\"\"\n" + text.slice(0, 4000) + "\n\"\"\"";
    return callGemini(prompt, { temperature: 0.3, maxOutputTokens: 4096 });
}

async function buildAiWorkflow(query) {
    if (!query || !query.trim()) throw new Error("Query cannot be empty.");
    const prompt = "You are a file processing AI for the Docholder platform. A user has typed a natural language command.\nParse their intent and return a structured workflow plan as a valid JSON object with this exact shape:\n\n{\n  \"intent\": \"<primary intent: convert|compress|merge|split|humanize|summarize|translate|analyze|watermark|extract|optimize>\",\n  \"steps\": [\n    { \"step\": 1, \"action\": \"<action name>\", \"description\": \"<user-friendly description>\" }\n  ],\n  \"estimatedTime\": \"<e.g. ~5 seconds>\",\n  \"confidence\": <0.0 to 1.0>,\n  \"clarification\": \"<optional: if the query is ambiguous, ask one short clarifying question, otherwise null>\"\n}\n\nUser command: \"" + query + "\"";
    const raw = await callGemini(prompt, { temperature: 0.3, maxOutputTokens: 512 });
    const jsonMatch = raw.match(/\{[\s\S]*\}/);
    if (!jsonMatch) throw new Error("Gemini did not return a valid workflow plan.");
    return JSON.parse(jsonMatch[0]);
}

module.exports = {
    generateText,
    humanizeText,
    analyzeAiContent,
    summarizeText,
    translateText,
    buildAiWorkflow,
    isConfigured: function() { return !!process.env.GEMINI_API_KEY; }
};
