const express = require('express');
const router = express.Router();
const filesController = require('../controllers/files.controller');
const authMiddleware = require('../middleware/auth');
const uploadMiddleware = require('../middleware/upload');

router.use(authMiddleware);

router.post('/upload', uploadMiddleware.single('file'), filesController.uploadFile);
router.get('/', filesController.listFiles);
router.get('/usage', filesController.getUsage);
router.post('/push-token', filesController.registerPushToken);
router.post('/ai-detector', uploadMiddleware.single('file'), filesController.aiDetector);
router.post('/humanize', filesController.humanize);
router.post('/understand', uploadMiddleware.single('file'), filesController.understand);
router.post('/chat', filesController.chat);
router.post('/cross-intelligence', filesController.crossIntelligence);
router.post('/fact-check', uploadMiddleware.single('file'), filesController.factCheck);
router.post('/diff', uploadMiddleware.array('files', 2), filesController.diff);
router.post('/dna', uploadMiddleware.single('file'), filesController.dna);
router.post('/health', uploadMiddleware.single('file'), filesController.health);
router.post('/fix-everything', uploadMiddleware.single('file'), filesController.fixEverything);
router.post('/goal-optimize', uploadMiddleware.single('file'), filesController.goalOptimize);
router.post('/smart-package', uploadMiddleware.array('files', 20), filesController.smartPackage);
router.post('/suggest-name', uploadMiddleware.single('file'), filesController.suggestName);
router.post('/classify', uploadMiddleware.single('file'), filesController.classify);
router.post('/privacy-scan', uploadMiddleware.single('file'), filesController.privacyScan);
router.post('/redact-pii', uploadMiddleware.single('file'), filesController.redactPii);
router.post('/translate', uploadMiddleware.single('file'), filesController.translate);
router.post('/spreadsheet-intelligence', uploadMiddleware.single('file'), filesController.spreadsheetIntelligence);
router.post('/generate-charts', uploadMiddleware.single('file'), filesController.generateCharts);
router.post('/share-link', filesController.shareLink);
router.post('/vault', filesController.vault);
router.post('/download-zip', filesController.downloadMultipleAsZip);
router.get('/:id/inspect', filesController.inspectFile);
router.get('/:id', filesController.getFile);
router.get('/:id/download', filesController.downloadFile);
router.delete('/:id', filesController.deleteFile);
router.put('/:id/rename', filesController.renameFile);
router.put('/:id/content', filesController.updateFileContent);
router.post('/:id/watermark/frontend', filesController.saveWatermarkRemoved);

module.exports = router;
